ALTER TABLE t_p78845984_auto_house_cost_calc.proposals
  ADD COLUMN IF NOT EXISTS delivery_conditions TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS delivery_city VARCHAR(128) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS delivery_street VARCHAR(256) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS delivery_building VARCHAR(64) NOT NULL DEFAULT '';